---
- name: Validation
  import_tasks:
    file: validation.yaml

- name: Shared tasks
  import_tasks:
    file: shared.yaml

- name: Install Redis
  import_tasks:
    file: redis.yaml

- name: Install Redis sentinel
  import_tasks:
    file: sentinel.yaml
  when: sentinel_enabled

- name: Install Redis exporter
  import_tasks:
    file: redis-exporter.yaml
  when: install_redis_exporter
