---
- name: Validate variables
  fail:
    msg: cluster_enabled and sentinel_enabled can't be enabled at the same time
  when: sentinel_enabled and cluster_enabled

- name: Shared tasks
  import_tasks:
    file: shared.yaml

- name: Install Redis
  import_tasks:
    file: redis.yaml

- name: Install Redis sentinel
  import_tasks:
    file: sentinel.yaml
  when: sentinel_enabled

- name: Install Redis exporter
  import_tasks:
    file: sentinel.yaml
  when: install_redis_exporter
