---
- name: Ensure necessary packages exist
  apt:
    update_cache: yes
    cache_valid_time: 3600
    state: present
  loop:
    - curl
    - gpg
    - lsb-release
    - logrotate

- name: Updating kernel configs
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "present"
    reload: true
  loop: 
    - name: vm.overcommit_memory
      value: "1"
    - name: net.ipv4.tcp_max_syn_backlog
      value: "16384"
    - name: net.core.somaxconn
      value: "16384"
    - name: vm.swappiness
      value: "0"
    - name: net.ipv4.tcp_window_scaling
      value: "1"
    - name: net.core.rmem_max
      value: "2097152" # 2MB
    - name: net.core.wmem_max
      value: "2097152" # 2MB
  
- name: Disabling transparent huge pages
  lineinfile:
    dest: /etc/default/grub
    state: present
    line: 'GRUB_CMDLINE_LINUX="transparent_hugepage=never $GRUB_CMDLINE_LINUX"'
  register: grub

- name: Rebuilding grub config file
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub.changed

- name: Reboot server 
  reboot:
    reboot_timeout: 1200
  when: grub.changed
